src/Entity/Pin.php
<?php

namespace App\Entity;

use App\Entity\Traits\Timestampable;
use App\Repository\PinRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity(repositoryClass=PinRepository::class)
 * @ORM\Table(name="pins")
 * @Vich\Uploadable
 * @ORM\HasLifecycleCallbacks()
 */
class Pin
{
    use Timestampable;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(
     *      min = 2,
     *      max = 40,
     *      minMessage = "Your title must be at least {{ limit }} characters long",
     *      maxMessage = "Your title cannot be longer than {{ limit }} characters")
     */
    private ?string $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     * @Assert\Length(
     *      min = 10,
     *      max = 100,
     *      minMessage = "Your description must be at least {{ limit }} characters long",
     *      maxMessage = "Your description cannot be longer than {{ limit }} characters")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageName;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * @Vich\UploadableField(mapping="pin_image", fileNameProperty="imageName")
     * @Assert\File(
     * maxSize="40Mi",
     * maxSizeMessage="Le fichier excède 8M.",
     * mimeTypes={"image/png", "image/jpeg", "image/jpg", "image/svg+xml", "image/gif"},
     * mimeTypesMessage= "formats autorisés: png, jpeg, jpg, svg, gif",
     * binaryFormat="false")
     */
    private $imageFile;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="pins")
     * @ORM\JoinColumn(nullable=false)
     */
    private ?User $user;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="pins")
     * @ORM\JoinColumn(nullable=false)
//     * @Assert\NotBlank(message="You must create a pin with a category")
     */
    private ?Category $category;

    private ?Category $nameCategory;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @param File|UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->setUpdatedAt(new \DateTimeImmutable);
        }
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }


    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Category|null
     *
     */
    public function getNameCategory(): ?Category
    {
        return $this->nameCategory;
    }

    /**
     * @param Category|null $nameCategory
     */
    public function setNameCategory(?Category $nameCategory): void
    {
        $this->nameCategory = $nameCategory;
    }

    public function getOwner(): ?User
    {
        $idPin= $this->getId();
       return $this->getUser($idPin);
    }


}

src/Form/PinType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Pin;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class PinType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder
            ->add('category', EntityType::class,[
                'class'=>Category::class,
                'required'=>true,
                'placeholder'=>'choose an option',
                'choice_label'=>'nameCategory',
                'multiple'=>false,
                'expanded'=>false,

            ])
            ->add('imageFile', VichImageType::class, [
                'label'=>'Image',
                'required' => false,
                'allow_delete' => true,
                'delete_label' => 'Delete?',
                'download_label' => 'Download Image',
                'download_uri' => false,
                'imagine_pattern' => 'squared_thumbnail_small',

            ])

            ->add('title', TextType::class)
            ->add('description',TextareaType::class);


    }

    /**
     * @param OptionsResolver $resolver
     * configure les options du formulaire, par défaut nous lui passons l'entité Pin
     * de ce fait, il va regarder dans l'entité le type des propriétés que nous avons passé lors de la creation de l'entité
     * je n'ai plus besoin de specifier dans le formulaire ci-dessus que description est de type textarea
     * il verra que c'est une propriété de type text donc il va le gérer automatiquement
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Pin::class,
        ]);
    }
}

src/Controller/PinsController.php
<?php

namespace App\Controller;

use App\Entity\Pin;
use App\Form\PinType;
use App\Repository\PinRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PinsController extends AbstractController
{

    /**
     * @Route("/", name="app_home", methods="GET")
     * @param PinRepository $pinRepository
     * @return Response
     */
    public function index(PinRepository $pinRepository): Response
    {
         $pins = $pinRepository->findBy([],['createdAt'=>'DESC']);
        return $this->render('pins/index.html.twig', compact('pins'));
    }

    /**
     * @IsGranted("ROLE_USER")
     * @Route("/pins/create", name="app_pin_create", methods={"GET", "POST"})
     * @param Request $request
     * @param EntityManagerInterface $em
     * @return Response
     */
    public function create(Request $request, EntityManagerInterface $em) : Response
    {
        $pin = new Pin();
        $form = $this->createForm(PinType::class, $pin);
        //récupère les données du formulaires via les requêtes
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $pin->setUser($this->getUser());
            $em->persist($pin);
            $em->flush();

            $this->addFlash('success','Pin successfully created!');
            return $this->redirectToRoute('app_home');

        }
        return $this->render('pins/create.html.twig',[
            'form'=>$form->createView()
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * la route est le pins suivi de l'id avec une obligation d'être des chiffres
     * @Route("/pins/{id<[0-9]+>}", name="app_pins_show", methods="GET")
     * @param Pin $pin //va prendre l'id
     * @return Response
     */
    public function show(Pin $pin): Response
    {
        $user =$this->getUser();
        return $this->render('pins/show.html.twig', ['pin'=>$pin, 'user'=>$user]);
    }

    /**
     * @Route("/pins/{id<[0-9]+>}/edit", name="app_pins_edit", methods={"GET", "PUT", "POST"})
     * @param Pin $pin
     * @param Request $request
     * @param EntityManagerInterface $em
     * @return Response
     */
    public function edit(Pin $pin, Request $request,EntityManagerInterface $em): Response
    {


        if (($pin->getOwner() !== $this->getUser()) and ($this->getUser()->getRoles() == ['ROLE_USER'])) {
//            throw $this->createAccessDeniedException();

            $this->addFlash('error','Access Denied');
            return $this->redirectToRoute('app_home');
        }

        //je fais appel au formulaire que j'ai créé via la commande make:form,
        // puis je lui dis d'utiliser la methode PUT qui est recommandée pour edit
        $form = $this->createForm(PinType::class, $pin, [
            'method'=> 'PUT'
        ]);
        //récupère les données du formulaires via les requêtes
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){

            $em->persist($pin);
            $em->flush();
            $this->addFlash('success','Pin successfully updated!');
            return $this->redirectToRoute('app_home');

        }
        return $this->render('pins/edit.html.twig', [
            'pin'=>$pin,
            'form'=>$form->createView()
        ]);
    }

    /**
     * @Route("/pins/{id<[0-9]+>}", name="app_pins_delete", methods={"DELETE"})
     * @param Request $request
     * @param Pin $pin
     * @param EntityManagerInterface $em
     * @return Response
     */
    public function delete(Request $request, Pin $pin, EntityManagerInterface $em): Response
    {


        if (($pin->getOwner() !== $this->getUser()) and ($this->getUser()->getRoles() == ['ROLE_USER'])) {

            $this->addFlash('error','Access Denied');
            return $this->redirectToRoute('app_home');
        }
        if($this->isCsrfTokenValid('pin_deletion_'. $pin->getId(),$request->request->get('csrf_token'))){
            $em->remove($pin);
            $em->flush();
        }
        $this->addFlash('info','Pin successfully deleted!');
        return $this->redirectToRoute('app_home');
    }

}

templates/pins/_form.html.twig
{{ form_start(form) }}
{{ form_row(form.category) }}
<p class="createCat text-center mt-5 text-muted"style="font-size: 15px">If you not found category, you can it create here?
    <button class=" btn-dark rounded ml-3" style="height: 30px"><a style="text-decoration: none;color: white ; font-size: 10px" href="{{ path('app_category_create') }}" >Let's go!</a></button></p>
{{ form_row(form.imageFile) }}
{{ form_row(form.title) }}
{{ form_row(form.description) }}
<input type="submit" value="{{ submitButtonText ?? 'Create Pin' }}"class="btn btn-primary btn-block btn-lg mb-5" formnovalidate>
{{ form_end(form) }}

templates/pins/create.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title 'New Pin' %}

{% block body %}
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h1 class=" h3 text-center mt-1 mb-3">Create Pin</h1>
            {{ include('pins/_form.html.twig') }}
        </div>
    </div>
{% endblock %}

templates/pins/edit.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title 'Edit Pin' ~ pin.id %}

{% block body %}
    <div class="row">
        <div>
            <button class="btn btn-dark "><a style="color: white; text-decoration: none" href="{{ path('app_pins_show', {id: pin.id}) }}">Go
                    Back</a></button>
        </div>
        <div class="col-md-6 mx-auto">
            <h1 class="h3 text-center mb-4 mt-3">Edit Pin {{ pin.title }}</h1>
            {{ include('pins/_form.html.twig', {submitButtonText: 'Update Pin'}) }}
        </div>
    </div>

{% endblock %}

templates/pins/index.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title 'Find All the best pins on earth!' %}

{% block body %}
    {% if pins|length > 0 %}
    {# Creation d'une fonction dans une class d'extension permettant de mettre au singulier ou pluriel Pin en fonction du nombre d'éléments #}
        <h1 class="text-center text-muted h4 mt-1 mb-2">{{ pluralize(pins|length, 'Post') }}</h1>
        {% for row in pins|batch(3)%}
            <div class="row mb-2">
                    {% for pin in row %}
                        <div class="col-md-4 ">
                            <article class="bg-white rounded shadow pin">
                                <div class="text-center ">
                                    <h1 class="h5 title Cat">{{ pin.category.nameCategory}}</h1>
                                </div>
                                    <div class="mw-100 rounded-top overflow-hidden">
                                        <a href="{{ path('app_pins_show', {id: pin.id}) }}">
                                            <img class="image-index w-100" src="{{ (pin.imageName ? vich_uploader_asset(pin) : asset('build/image/placeholder.png'))
                                            | imagine_filter('squared_thumbnail_medium')}}" alt="{{pin.title}}" />
                                        </a>
                                    </div>
                                <h2 class="h5 pl-2 pt-2"><a class=" text-secondary text-decoration-none" href="{{ path('app_pins_show', {id: pin.id}) }}"><p class="overflow-title">{{ pin.title }}</p></a></h2>
                                <p class=" pl-3 pb-2 text-muted"><small>Submitted by {{pin.user.getFullName()}}</small></p>
                            </article>
                        </div>

                    {% endfor %}
            </div>
        {% endfor %}
    {% else %}
      <p class="mt-5 h1 text-center">No pins yet. <a href="{{ path('app_pin_create') }}">Create your Pin!</a> </p>
    {% endif %}
{% endblock %}

templates/pins/show.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title pin.title %}

{% block body %}
    <div class="row">
        <div class="mb-0">
            <button class="btn btn-dark "><a style="color: white; text-decoration: none" href="{{ path('app_home', {id: pin.id}) }}">Go
                    Back</a></button>
        </div>
        <div class=".col-md-6 mx-auto">
            <article class="bg-white rounded shadow pin">
                <div class="mw-100 rounded-top overflow-hidden mt-3">
                        <img class="image-index w-100" src="{{ (pin.imageName ? vich_uploader_asset(pin) : asset('build/image/placeholder.png'))
                        | imagine_filter('squared_thumbnail_medium')}}" alt="{{pin.title}}" />
                </div>
                <p class=" pl-1  text-muted comment">
                    <small>Submitted <time datetime="{{ pin.createdAt|date('Y-m-d H:i:s') }}">{{ pin.createdAt|ago }}</time> by {{ pin.user.getFullName() }}</small>
                </p>
                <h1 class="h5 pl-2 text-secondary"><p class="overflow-title">{{ pin.title }}</p></h1>

                {# Description du pin #}
                <h5 class="titleDescription">Details: </h5><br>
                <p class="overflow-description pb-2">
                {{ pin.description }}
                </p>
               {% if((pin.owner == user) or (user.roles() == ['ROLE_ADMIN','ROLE_USER'])) %}
                <div class="pb-3 buttonEdit">
                    <a href="{{ path('app_pins_edit', {id: pin.id}) }}" class="btn btn-light">Edit</a>
                    {# lien delete qui recupère le form grace à son id #}
                    <a href="#" onclick="event.preventDefault();confirm('Are you sure delete the {{ pin.title }} ?')
                            && document.getElementById('js-pin-delete-form').submit();" class="btn btn-light">Delete</a>
                    {#
                    form qui sera pas affiché qui prend la methode POST initialement mais que je vais forcer en methode DELETE et
                    j'ajoute un champ caché qui est une securité csrf qui permet de généré un token pour securiser le formulaire
                    #}
                    <form id="js-pin-delete-form" action="{{ path('app_pins_delete', {id: pin.id}) }}" method="post" style="display: none;">
                        <input type="hidden" name="csrf_token" id="" value="{{ csrf_token('pin_deletion_' ~ pin.id) }}">
                        <input type="hidden" name="_method" value="DELETE">
                    </form>
                </div>
                {% endif %}
            </article>
        </div>
    </div>
{% endblock %}