src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Traits\Timestampable;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="users")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(fields="email", message="There is already an account with this email")
 */
class User implements UserInterface
{
    use Timestampable;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private  $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Please you must give your first name")
     *  @Assert\Regex(pattern="/\d/", match=false, message="Cannot contain a number")
     * @Assert\Length(
     *      min = 2,
     *      max = 50,
     *      minMessage = "Your first name must be at least {{ limit }} characters long",
     *      maxMessage = "Your first name cannot be longer than {{ limit }} characters")
     */
    private  $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Please you must give your last name")
     * @Assert\Regex(pattern="/\d/", match=false, message="Cannot contain a number")
     * @Assert\Length(
     *      min = 2,
     *      max = 50,
     *      minMessage = "Your first name must be at least {{ limit }} characters long",
     *      maxMessage = "Your first name cannot be longer than {{ limit }} characters")
     */
    private  $lastName;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\NotBlank(message="Please you must give your email address")
     * @Assert\Email(message="Your email address isen't valid")
     */
    private  $email;

    /**
     * @ORM\Column(type="json")
     */
    private  $roles = ['ROLE_USER'];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private  $password;

    /**
     * @ORM\OneToMany(targetEntity=Pin::class, mappedBy="user", orphanRemoval=true)
     */
    private  $pins;

    /**
     * @ORM\Column(type="boolean")
     */
    private  $isVerified = false;

    public function __construct()
    {
        $this->pins = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFullName(): string
    {
       return $this->getFirstName()." ".$this->getLastName();
    }

    public function avatar(?int $size=100)
    {
        return sprintf('https://www.gravatar.com/avatar/%s?s=%d', md5(strtolower($this->getEmail())), $size);
    }
    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Pin[]
     */
    public function getPins(): Collection
    {
        return $this->pins;
    }

    public function addPin(Pin $pin): self
    {
        if (!$this->pins->contains($pin)) {
            $this->pins[] = $pin;
            $pin->setUser($this);
        }

        return $this;
    }

    public function removePin(Pin $pin): self
    {
        if ($this->pins->removeElement($pin)) {
            // set the owning side to null (unless already changed)
            if ($pin->getUser() === $this) {
                $pin->setUser(null);
            }
        }

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }



}

templates/layouts/partials/_flash_messages.html.twig
{% block flash_messages %}
    {% for type, messages in app.session.flashbag.all() %}
        {% for message in messages %}
            <div class="alert alert-{{ type }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                {{ message | raw }}
            </div>
        {% endfor %}
    {% endfor %}
{% endblock %}

templates/layouts/partials/_footer.html.twig
<div class="card text-center mt-5 fixed-bottom">

    <div class="card-body mt-0">
        <a href="{{ path('app_home') }}" class="btn btn-light mt-2 mb-1">Go Back Home</a>
    </div>
    <p>
        <small>
            &copy; {{ 'now'|date('Y') }} &middot;
            Built by David Devaure <a href="https://www.linkedin.com/in/daviddevaure"> My Profile</a>
        </small>
    </p>
</div>

templates/layouts/partials/_nav.html.twig
<nav class="navbar navbar-expand-sm navbar-light bg-light fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{{ path('app_home') }}">Picterest</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03"
                aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample03">
            <ul class="navbar-nav ml-auto">
                {% if app.user %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('app_pin_create') }}">New Pin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('search_pin') }}">Search pin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('user_index') }}">Account</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="#" onclick="event.preventDefault(); document.getElementById('js-logout-form').submit();">Logout </a>
                    </li>
                    <form id="js-logout-form"  action="{{ path('app_logout') }}" method="POST" style="display: none;">
                        <input type="hidden" name="_csrf_token" value="{{ csrf_token('logout') }}">
                    </form>

                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('app_register') }}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('app_login') }}">Login</a>
                    </li>
                {% endif %}
                {% if is_granted('ROLE_ADMIN') %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('admin_app_list_user') }}">Admin</a>
                </li>
                {% endif %}
                {% if app.user %}
                    <div class=" row userLogged"> <img class="rounded" style="width:40px" src="{{ asset('build/image/profil.png')}}" alt="image logged">{{ app.user.fullName }}</div>
                {% endif %}
            </ul>
        </div>

    </div>

</nav>